workConfig:
  server:
    port: 3000

  db:
    type: 'postgres'
    port: 5432
    database: 'pfadftzl'
    host: 'ruby.db.elephantsql.com'
    username: 'pfadftzl'
    password: 'OqgjFi8q5wruyhCU1dQr6aAq2Kos8tdM'
    synchronize: true

  jwt: 
    expiresIn: 3600
    secret: 'topSecret51'